#!/usr/bin/env python3
"""Pack the songs in Songs/ so index.html can list and load them, even when opened from file://.

Browsers cannot read a folder or fetch local files from a double-clicked page, but they can
load <script> files. So each song is written as Songs/library/<id>.js (the audio as base64)
and Songs/library.js lists them for the "My Songs" screen.

Run it again whenever you add, remove or replace songs:
    py tools/build_library.py
"""
import base64
import hashlib
import json
import struct
import urllib.parse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SONGS = ROOT / "Songs"
OUT = SONGS / "library"
PACK_NAME = "Heather Music Hub songs.hmhpack"
EXTS = {".mp3", ".m4a", ".aac", ".wav", ".ogg", ".oga", ".opus", ".flac", ".webm"}


def _text(enc, raw):
    codec = {0: "latin-1", 1: "utf-16", 2: "utf-16-be", 3: "utf-8"}.get(enc, "latin-1")
    try:
        return raw.decode(codec).replace("\x00", "").lstrip("﻿").strip()
    except UnicodeDecodeError:
        return ""


def id3_tags(data):
    """Title / artist from ID3v2 (2.2-2.4), falling back to ID3v1."""
    tags = {}
    if data[:3] == b"ID3" and len(data) > 10:
        ver, flags = data[3], data[5]
        size = (data[6] & 0x7F) << 21 | (data[7] & 0x7F) << 14 | (data[8] & 0x7F) << 7 | (data[9] & 0x7F)
        pos, end = 10, min(10 + size, len(data))
        if flags & 0x40:  # extended header
            ext = struct.unpack(">I", data[10:14])[0]
            pos += ext if ver == 4 else ext + 4
        id_len, hdr = (3, 6) if ver == 2 else (4, 10)
        want = {"TT2": "title", "TP1": "artist"} if ver == 2 else {"TIT2": "title", "TPE1": "artist"}
        while pos + hdr < end:
            fid = data[pos:pos + id_len].decode("latin-1")
            if not fid.isalnum():
                break
            if ver == 2:
                fsize = int.from_bytes(data[pos + 3:pos + 6], "big")
            elif ver == 4:
                b = data[pos + 4:pos + 8]
                fsize = (b[0] & 0x7F) << 21 | (b[1] & 0x7F) << 14 | (b[2] & 0x7F) << 7 | (b[3] & 0x7F)
            else:
                fsize = struct.unpack(">I", data[pos + 4:pos + 8])[0]
            start = pos + hdr
            if fsize <= 0 or start + fsize > end:
                break
            if fid in want and fsize > 1:
                value = _text(data[start], data[start + 1:start + fsize])
                if value:
                    tags[want[fid]] = value
            pos = start + fsize
    if len(data) > 128 and data[-128:-125] == b"TAG":
        v1 = data[-128:]
        for key, raw in (("title", v1[3:33]), ("artist", v1[33:63])):
            value = raw.split(b"\x00")[0].decode("latin-1").strip()
            if value and key not in tags:
                tags[key] = value
    return tags


def mp4_tags(data):
    """Title / artist from iTunes-style metadata atoms (M4A / AAC)."""
    tags = {}
    for atom, key in ((b"\xa9nam", "title"), (b"\xa9ART", "artist")):
        i = data.find(atom)
        while i >= 4:
            size = struct.unpack(">I", data[i - 4:i])[0]
            if data[i + 8:i + 12] == b"data" and 16 < size < 4096:
                value = data[i + 20:i - 4 + size].decode("utf-8", "replace").strip()
                if value:
                    tags[key] = value
                break
            i = data.find(atom, i + 1)
    return tags


def main():
    if not SONGS.is_dir():
        sys.exit(f"No Songs folder at {SONGS}")
    OUT.mkdir(exist_ok=True)
    files = sorted((p for p in SONGS.iterdir() if p.is_file() and p.suffix.lower() in EXTS),
                   key=lambda p: p.name.lower())
    songs = []
    for p in files:
        data = p.read_bytes()
        sid = hashlib.sha1(data).hexdigest()[:12]
        bundle = OUT / f"{sid}.js"
        if not bundle.exists():
            b64 = base64.b64encode(data).decode("ascii")
            bundle.write_text(f'BeatTilesLibrary.receive("{sid}","{b64}");\n', encoding="ascii")
        tags = mp4_tags(data) if p.suffix.lower() in {".m4a", ".aac"} else id3_tags(data)
        songs.append({
            "id": sid,
            "file": p.name,
            "title": tags.get("title") or p.stem,
            "artist": tags.get("artist", ""),
            "size": len(data),
            "bundle": f"Songs/library/{sid}.js",
            # Used instead of the bundle when the page is served over http(s).
            "url": "Songs/" + urllib.parse.quote(p.name),
        })
        print(f"  {songs[-1]['title']}  ({p.name}, {len(data) / 1e6:.1f} MB)")

    keep = {s["id"] for s in songs}
    for old in OUT.glob("*.js"):
        if old.stem not in keep:
            old.unlink()

    manifest = json.dumps({"songs": songs}, ensure_ascii=True, indent=1)
    (SONGS / "library.js").write_text(
        "// Generated by tools/build_library.py - rerun it after changing the Songs folder.\n"
        f"window.BeatTilesLibrary = {manifest};\n", encoding="ascii")
    print(f"Packed {len(songs)} song(s) into Songs/library.js")
    write_pack(files, songs)


def write_pack(files, songs):
    """One file with every song, for the phone: copy it to iCloud Drive (or anywhere the Files
    app sees) and tap "Import song pack" in the app. Layout: b"HMHPACK1", header length
    (uint32 little-endian), JSON header, then the audio files back to back."""
    entries, blobs, offset = [], [], 0
    for p, s in zip(files, songs):
        data = p.read_bytes()
        entries.append({"file": s["file"], "title": s["title"], "artist": s["artist"],
                        "offset": offset, "size": len(data)})
        blobs.append(data)
        offset += len(data)
    header = json.dumps({"app": "HeatherMusicHub", "songs": entries}, ensure_ascii=False).encode("utf-8")
    pack = SONGS / PACK_NAME
    with open(pack, "wb") as f:
        f.write(b"HMHPACK1")
        f.write(struct.pack("<I", len(header)))
        f.write(header)
        for b in blobs:
            f.write(b)
    print(f"Wrote song pack: Songs/{PACK_NAME} ({offset / 1e6:.1f} MB)")


if __name__ == "__main__":
    main()
